/*INSERT INTO ROLES (ROLE_NAME,ROLE_DESCRIPTION) VALUES ('ADMIN','ADMIN ROLE');
INSERT INTO ROLES (ROLE_NAME,ROLE_DESCRIPTION) VALUES ('REGULAR USER','GENERIC ROLE');
INSERT INTO ROLES (ROLE_NAME,ROLE_DESCRIPTION) VALUES ('REPORTER','REPORTER ROLE');*/

INSERT INTO USER (FIRST_NAME,PASSWORD,LAST_NAME,EMAIL_ADDRESS,ACCOUNT_ORIGIN) VALUES ('JUAN','12345','GABRIEL','test@test.com','LOCAL');
INSERT INTO USER (FIRST_NAME,PASSWORD,LAST_NAME,EMAIL_ADDRESS,ACCOUNT_ORIGIN) VALUES ('PEDRO','12345','POBLANO','test2@test.com','LOCAL');
INSERT INTO USER (FIRST_NAME,PASSWORD,LAST_NAME,EMAIL_ADDRESS,ACCOUNT_ORIGIN) VALUES ('FRANCISCO','12345','PEREZ','test3@test.com','LOCAL');
INSERT INTO USER (FIRST_NAME,PASSWORD,LAST_NAME,EMAIL_ADDRESS,ACCOUNT_ORIGIN) VALUES ('GUILLERMO','12345','ALONSO','test4@test.com','LOCAL');
INSERT INTO USER (FIRST_NAME,PASSWORD,LAST_NAME,EMAIL_ADDRESS,ACCOUNT_ORIGIN) VALUES ('Cristhian','$2a$10$QDx7HKU/Xy1deGgAVDe5c.pbaebf9xvr6cxZ2oNytUVN4gaqJAtae','Urcuyo','cxurcuyo@gmail.com','LOCAL');


/*INSERT INTO USER_ROLE (USER_ROLE_ID,DURATION_TYPE,ROLE_ID,USER_ID)VALUES(1,'TEMPORAL',1,1);
INSERT INTO USER_ROLE (USER_ROLE_ID,DURATION_TYPE,ROLE_ID,USER_ID)VALUES(2,'TEMPORAL',2,1);
INSERT INTO USER_ROLE (USER_ROLE_ID,DURATION_TYPE,ROLE_ID,USER_ID)VALUES(3,'TEMPORAL',3,1);
INSERT INTO USER_ROLE (USER_ROLE_ID,DURATION_TYPE,ROLE_ID,USER_ID)VALUES(4,'TEMPORAL',1,5);*/